# Generated by Django 3.2.7 on 2021-10-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_in_sentences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
