# Generated by Django 3.2.9 on 2022-03-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_in_sentences', '0003_auto_20220224_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='modified_at',
            new_name='modified_time',
        ),
    ]
