# Generated by Django 3.2.12 on 2022-03-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words_in_sentences', '0004_auto_20220308_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_times', models.PositiveSmallIntegerField(default=0)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('last_review_date', models.DateField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words_in_sentences.sentence')),
            ],
        ),
    ]
