# Generated by Django 3.2.12 on 2022-03-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_in_sentences', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='version',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_understand',
        ),
    ]
